// The 77 theatre watches before the theatre source started (Sprint 10), with
// the year each was logged, read once from tiyatrolar.com.tr's relative
// times by scripts/theatre-history.ts. Onur checked the years on
// 2026-10-05. Edit a year here to correct it (the theatre archive step
// re-seeds every run, and readLifeLog merges this file in at read time).
// The oldest year is shown as "and earlier": it is the bulk entry made when
// the account was set up, which also holds plays seen before then.
//
// Generated file: re-run `npx tsx scripts/theatre-history.ts` only to
// rebuild it from scratch, then re-apply Onur's corrections.

export interface TheatreHistoryRow {
  // The tiyatrolar activity post id ("izledi").
  id: string;
  title: string;
  slug: string;
  company: string;
  poster: string;
  link: string;
  year: number;
}

export const theatreHistory: TheatreHistoryRow[] = [
  {"id":"1481396","title":"Adel Seni Seçti","slug":"adel-seni-secti-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/a/adel-seni-secti-1/image/adel-seni-secti-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/adel-seni-secti-1","year":2026}, // 3 gün önce
  {"id":"1477481","title":"İki","slug":"iki","company":"Bilkent International Laboratory Theatre (BILT)","poster":"https://tiyatrolar.com.tr/files/activity/i/iki/image/iki.jpg","link":"https://tiyatrolar.com.tr/tiyatro/iki","year":2026}, // 2 hafta önce
  {"id":"1462227","title":"Bazı Kötü Alışkanlıkların Politik Tarihi","slug":"bazi-kotu-aliskanliklarin-politik-tarihi","company":"Ara Sahne","poster":"https://tiyatrolar.com.tr/files/activity/b/bazi-kotu-aliskanliklarin-politik-tarihi/image/bazi-kotu-aliskanliklarin-politik-tarihi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/bazi-kotu-aliskanliklarin-politik-tarihi","year":2026}, // 5 ay önce
  {"id":"1454532","title":"Ballı Süt","slug":"balli-sut","company":"Kadar","poster":"https://tiyatrolar.com.tr/files/activity/b/balli-sut/image/balli-sut.jpg","link":"https://tiyatrolar.com.tr/tiyatro/balli-sut","year":2026}, // 6 ay önce
  {"id":"1437325","title":"Serin Bir Sabah","slug":"serin-bir-sabah","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/s/serin-bir-sabah/image/serin-bir-sabah.jpg","link":"https://tiyatrolar.com.tr/tiyatro/serin-bir-sabah","year":2026}, // 7 ay önce
  {"id":"1430493","title":"İçerde Polis Var","slug":"icerde-polis-var","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/i/icerde-polis-var/image/icerde-polis-var.jpg","link":"https://tiyatrolar.com.tr/tiyatro/icerde-polis-var","year":2026}, // 7 ay önce
  {"id":"1426665","title":"Esaretin Bedeli","slug":"esaretin-bedeli-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/e/esaretin-bedeli-1/image/esaretin-bedeli-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/esaretin-bedeli-1","year":2026}, // 7 ay önce
  {"id":"1405458","title":"Marilyn - Venüs'ün Son Gecesi","slug":"marilyn-venusun-son-gecesi","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/m/marilyn-venusun-son-gecesi/image/marilyn-venusun-son-gecesi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/marilyn-venusun-son-gecesi","year":2026}, // 9 ay önce
  {"id":"1401254","title":"Şakşakçılar","slug":"saksakcilar","company":"TiyatrOPS","poster":"https://tiyatrolar.com.tr/files/activity/s/saksakcilar/image/saksakcilar.jpg","link":"https://tiyatrolar.com.tr/tiyatro/saksakcilar","year":2026}, // 9 ay önce
  {"id":"1391015","title":"Berlin Berlin (Duvarın Gölgesinde Bir Komedi)","slug":"berlin-berlin-duvarin-golgesinde-bir-komedi","company":"Sivas Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/b/berlin-berlin-duvarin-golgesinde-bir-komedi/image/berlin-berlin-duvarin-golgesinde-bir-komedi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/berlin-berlin-duvarin-golgesinde-bir-komedi","year":2026}, // 9 ay önce
  {"id":"1377725","title":"Herkes Kocama Benziyor","slug":"herkes-kocama-benziyor-1","company":"Temsili Sahne","poster":"https://tiyatrolar.com.tr/files/activity/h/herkes-kocama-benziyor-1/image/herkes-kocama-benziyor-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/herkes-kocama-benziyor-1","year":2025}, // 10 ay önce
  {"id":"1365686","title":"Sherlock Holmes, Baskerviller'in Köpeği","slug":"sherlock-holmes-baskervillerin-kopegi","company":"Fikir Sanat Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/s/sherlock-holmes-baskervillerin-kopegi/image/sherlock-holmes-baskervillerin-kopegi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/sherlock-holmes-baskervillerin-kopegi","year":2025}, // 11 ay önce
  {"id":"1363474","title":"American Blues","slug":"american-blues","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/a/american-blues/image/american-blues.jpg","link":"https://tiyatrolar.com.tr/tiyatro/american-blues","year":2025}, // 11 ay önce
  {"id":"1363473","title":"77. Şube","slug":"77-sube","company":"Bilkent International Laboratory Theatre (BILT)","poster":"https://tiyatrolar.com.tr/files/activity/7/77-sube/image/77-sube.jpg","link":"https://tiyatrolar.com.tr/tiyatro/77-sube","year":2025}, // 11 ay önce
  {"id":"1363472","title":"The Blue Hotel","slug":"the-blue-hotel","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/t/the-blue-hotel/image/the-blue-hotel.jpg","link":"https://tiyatrolar.com.tr/tiyatro/the-blue-hotel","year":2025}, // 11 ay önce
  {"id":"1363471","title":"Devinim","slug":"devinim","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/d/devinim/image/devinim.jpg","link":"https://tiyatrolar.com.tr/tiyatro/devinim","year":2025}, // 11 ay önce
  {"id":"1363470","title":"Öfke","slug":"ofke","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/o/ofke/image/ofke.jpg","link":"https://tiyatrolar.com.tr/tiyatro/ofke","year":2025}, // 11 ay önce
  {"id":"1363469","title":"Madde 22","slug":"madde-22","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/m/madde-22/image/madde-22.jpg","link":"https://tiyatrolar.com.tr/tiyatro/madde-22","year":2025}, // 11 ay önce
  {"id":"1363344","title":"Bu da Geçer Ya Hu","slug":"bu-da-gecer-ya-hu-2","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/b/bu-da-gecer-ya-hu-2/image/bu-da-gecer-ya-hu-2.jpg","link":"https://tiyatrolar.com.tr/tiyatro/bu-da-gecer-ya-hu-2","year":2025}, // 11 ay önce
  {"id":"1358966","title":"Bobik Nerede?","slug":"bobik-nerede","company":"Mim Kolektif","poster":"https://tiyatrolar.com.tr/files/activity/b/bobik-nerede/image/bobik-nerede.jpg","link":"https://tiyatrolar.com.tr/tiyatro/bobik-nerede","year":2025}, // 11 ay önce
  {"id":"1358345","title":"Işıltılı Haşerat","slug":"isiltili-haserat-2","company":"İstanbul Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/i/isiltili-haserat-2/image/isiltili-haserat-2.jpg","link":"https://tiyatrolar.com.tr/tiyatro/isiltili-haserat-2","year":2025}, // 11 ay önce
  {"id":"1353174","title":"Yıldız","slug":"yildiz","company":"artalan kolektif","poster":"https://tiyatrolar.com.tr/files/activity/y/yildiz/image/yildiz.jpg","link":"https://tiyatrolar.com.tr/tiyatro/yildiz","year":2025}, // 1 yıl önce
  {"id":"1351721","title":"Bir Delinin Hatıra Defteri","slug":"bir-delinin-hatira-defteri3","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/b/bir-delinin-hatira-defteri3/image/bir-delinin-hatira-defteri3.jpg","link":"https://tiyatrolar.com.tr/tiyatro/bir-delinin-hatira-defteri3","year":2025}, // 1 yıl önce
  {"id":"1345323","title":"Yetimler","slug":"yetimler","company":"Etimesgut Kent Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/y/yetimler/image/yetimler.jpg","link":"https://tiyatrolar.com.tr/tiyatro/yetimler","year":2025}, // 1 yıl önce
  {"id":"1340648","title":"Kuşkondu Müzikali","slug":"kuskondu-muzikali","company":"Etimesgut Kent Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/k/kuskondu-muzikali/image/kuskondu-muzikali.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kuskondu-muzikali","year":2025}, // 1 yıl önce
  {"id":"1334399","title":"12 Öfkeli","slug":"12-ofkeli","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/1/12-ofkeli/image/12-ofkeli.jpg","link":"https://tiyatrolar.com.tr/tiyatro/12-ofkeli","year":2025}, // 1 yıl önce
  {"id":"1331384","title":"Linçler ve Dudaklar","slug":"lincler-ve-dudaklar","company":"Dolkun Production","poster":"https://tiyatrolar.com.tr/files/activity/l/lincler-ve-dudaklar/image/lincler-ve-dudaklar.jpg","link":"https://tiyatrolar.com.tr/tiyatro/lincler-ve-dudaklar","year":2025}, // 1 yıl önce
  {"id":"1327751","title":"Nora (Bir Bebek Evi)","slug":"nora-bir-bebek-evi-2","company":"Tiyatro Circa","poster":"https://tiyatrolar.com.tr/files/activity/n/nora-bir-bebek-evi-2/image/nora-bir-bebek-evi-2.jpg","link":"https://tiyatrolar.com.tr/tiyatro/nora-bir-bebek-evi-2","year":2025}, // 1 yıl önce
  {"id":"1326596","title":"Majestik","slug":"majestik","company":"İzmir Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/m/majestik/image/majestik.jpg","link":"https://tiyatrolar.com.tr/tiyatro/majestik","year":2025}, // 1 yıl önce
  {"id":"1324012","title":"Ebedi Barış","slug":"ebedi-baris-1","company":"İstanbul Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/e/ebedi-baris-1/image/ebedi-baris-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/ebedi-baris-1","year":2025}, // 1 yıl önce
  {"id":"1322767","title":"Arzuları Yerine Getirme Müdürlüğü","slug":"arzulari-yerine-getirme-mudurlugu","company":"Bilkent International Laboratory Theatre (BILT)","poster":"https://tiyatrolar.com.tr/files/activity/a/arzulari-yerine-getirme-mudurlugu/image/arzulari-yerine-getirme-mudurlugu.jpg","link":"https://tiyatrolar.com.tr/tiyatro/arzulari-yerine-getirme-mudurlugu","year":2025}, // 1 yıl önce
  {"id":"1304241","title":"İnsanlığımı Yitirirken","slug":"insanligimi-yitirirken","company":"Tiyatral Sanat ve Kültür","poster":"https://tiyatrolar.com.tr/files/activity/i/insanligimi-yitirirken/image/insanligimi-yitirirken.jpg","link":"https://tiyatrolar.com.tr/tiyatro/insanligimi-yitirirken","year":2025}, // 1 yıl önce
  {"id":"1275898","title":"La Ronde","slug":"la-ronde","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/l/la-ronde/image/la-ronde.jpg","link":"https://tiyatrolar.com.tr/tiyatro/la-ronde","year":2024}, // 2 yıl önce
  {"id":"1275892","title":"Kuvayi Milliye Destanı","slug":"kuvayi-milliye-destani-2","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/k/kuvayi-milliye-destani-2/image/kuvayi-milliye-destani-2.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kuvayi-milliye-destani-2","year":2024}, // 2 yıl önce
  {"id":"1275881","title":"Kan Kardeşler","slug":"kan-kardesler","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/k/kan-kardesler/image/kan-kardesler.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kan-kardesler","year":2024}, // 2 yıl önce
  {"id":"1190135","title":"Gidion'un Düğümü","slug":"gidionun-dugumu-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/g/gidionun-dugumu-1/image/gidionun-dugumu-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/gidionun-dugumu-1","year":2024}, // 2 yıl önce
  {"id":"1171902","title":"Küvetteki Gelinler","slug":"kuvetteki-gelinler","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/k/kuvetteki-gelinler/image/kuvetteki-gelinler.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kuvetteki-gelinler","year":2024}, // 2 yıl önce
  {"id":"1161612","title":"Batı Ekspresi","slug":"bati-ekspresi","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/b/bati-ekspresi/image/bati-ekspresi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/bati-ekspresi","year":2024}, // 2 yıl önce
  {"id":"1111297","title":"Glengarry Glen Ross","slug":"glengarry-glen-ross","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/g/glengarry-glen-ross/image/glengarry-glen-ross.jpg","link":"https://tiyatrolar.com.tr/tiyatro/glengarry-glen-ross","year":2024}, // 2 yıl önce
  {"id":"1045043","title":"Dogville","slug":"dogville-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/d/dogville-1/image/dogville-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/dogville-1","year":2023}, // 3 yıl önce
  {"id":"918593","title":"Kim Bu Ben","slug":"kim-bu-ben","company":"Tiyatro.iN","poster":"https://tiyatrolar.com.tr/files/activity/k/kim-bu-ben/image/kim-bu-ben.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kim-bu-ben","year":2023}, // 3 yıl önce
  {"id":"903629","title":"Fahrenheit 451","slug":"fahrenheit-451","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/f/fahrenheit-451/image/fahrenheit-451.jpg","link":"https://tiyatrolar.com.tr/tiyatro/fahrenheit-451","year":2023}, // 3 yıl önce
  {"id":"894431","title":"Sefiller","slug":"sefiller-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/s/sefiller-1/image/sefiller-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/sefiller-1","year":2023}, // 3 yıl önce
  {"id":"885544","title":"Sıfır Telaş","slug":"sifir-telas","company":"Tiyatroperest","poster":"https://tiyatrolar.com.tr/files/activity/s/sifir-telas/image/sifir-telas.jpg","link":"https://tiyatrolar.com.tr/tiyatro/sifir-telas","year":2023}, // 3 yıl önce
  {"id":"677118","title":"Toplu Hikayeler","slug":"toplu-hikayeler-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/t/toplu-hikayeler-1/image/toplu-hikayeler-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/toplu-hikayeler-1","year":2022}, // 4 yıl önce
  {"id":"677115","title":"Gölge Ustası","slug":"golge-ustasi-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/g/golge-ustasi-1/image/golge-ustasi-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/golge-ustasi-1","year":2022}, // 4 yıl önce
  {"id":"677110","title":"Bunu Edgar Allan Poe Bile Hayal Edemezdi!","slug":"bunu-edgar-allan-poe-bile-hayal-edemezdi","company":"Tiyatro Libra","poster":"https://tiyatrolar.com.tr/files/activity/b/bunu-edgar-allan-poe-bile-hayal-edemezdi/image/bunu-edgar-allan-poe-bile-hayal-edemezdi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/bunu-edgar-allan-poe-bile-hayal-edemezdi","year":2022}, // 4 yıl önce
  {"id":"677101","title":"Eksi Bir","slug":"eksi-bir","company":"Farabi Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/e/eksi-bir/image/eksi-bir.jpg","link":"https://tiyatrolar.com.tr/tiyatro/eksi-bir","year":2022}, // 4 yıl önce
  {"id":"656877","title":"Sokrates'in Son Gecesi","slug":"sokratesin-son-gecesi-2","company":"Çankaya Sahne","poster":"https://tiyatrolar.com.tr/files/activity/s/sokratesin-son-gecesi-2/image/sokratesin-son-gecesi-2.jpg","link":"https://tiyatrolar.com.tr/tiyatro/sokratesin-son-gecesi-2","year":2022}, // 4 yıl önce
  {"id":"627497","title":"Koleksiyoncu","slug":"koleksiyoncu-1","company":"KÖK Sahne Sanatları","poster":"https://tiyatrolar.com.tr/files/activity/k/koleksiyoncu-1/image/koleksiyoncu-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/koleksiyoncu-1","year":2021}, // 5 yıl önce
  {"id":"519890","title":"Dr. Jekyll İle Bay Hyde","slug":"dr-jekyll-ile-bay-hyde","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/d/dr-jekyll-ile-bay-hyde/image/dr-jekyll-ile-bay-hyde.jpg","link":"https://tiyatrolar.com.tr/tiyatro/dr-jekyll-ile-bay-hyde","year":2021}, // 5 yıl önce
  {"id":"518058","title":"Kadınlarımız","slug":"kadinlarimiz-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/k/kadinlarimiz-1/image/kadinlarimiz-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kadinlarimiz-1","year":2021}, // 5 yıl önce
  {"id":"518056","title":"Gökkuşağının Sonu","slug":"gokkusaginin-sonu","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/g/gokkusaginin-sonu/image/gokkusaginin-sonu.jpg","link":"https://tiyatrolar.com.tr/tiyatro/gokkusaginin-sonu","year":2021}, // 5 yıl önce
  {"id":"424183","title":"Dr. Korczak Örneği","slug":"dr-korczak-ornegi","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/d/dr-korczak-ornegi/image/dr-korczak-ornegi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/dr-korczak-ornegi","year":2019}, // 7 yıl önce
  {"id":"248139","title":"Fare Kapanı","slug":"fare-kapani-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/f/fare-kapani-1/image/fare-kapani-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/fare-kapani-1","year":2018}, // 8 yıl önce
  {"id":"248135","title":"Tüy Kalemler","slug":"tuy-kalemler","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/t/tuy-kalemler/image/tuy-kalemler.jpg","link":"https://tiyatrolar.com.tr/tiyatro/tuy-kalemler","year":2018}, // 8 yıl önce
  {"id":"230120","title":"Reis Bey","slug":"reis-bey-1","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/r/reis-bey-1/image/reis-bey-1.jpg","link":"https://tiyatrolar.com.tr/tiyatro/reis-bey-1","year":2017}, // 9 yıl önce
  {"id":"166443","title":"Japon Kuklası","slug":"japon-kuklasi","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/j/japon-kuklasi/image/japon-kuklasi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/japon-kuklasi","year":2016}, // 10 yıl önce
  {"id":"150735","title":"1806 Laveyn","slug":"1806-laveyn","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/1/1806-laveyn/image/1806-laveyn.jpg","link":"https://tiyatrolar.com.tr/tiyatro/1806-laveyn","year":2016}, // 10 yıl önce
  {"id":"147389","title":"Gidion'un Düğümü","slug":"gidionun-dugumu","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/g/gidionun-dugumu/image/gidionun-dugumu.jpg","link":"https://tiyatrolar.com.tr/tiyatro/gidionun-dugumu","year":2016}, // 10 yıl önce
  {"id":"103205","title":"Moby Dick - Beyaz Balina","slug":"moby-dick-beyaz-balina","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/m/moby-dick-beyaz-balina/image/moby-dick-beyaz-balina.jpg","link":"https://tiyatrolar.com.tr/tiyatro/moby-dick-beyaz-balina","year":2015}, // 11 yıl önce
  {"id":"97888","title":"Lefty'i Beklerken","slug":"lefty-i-beklerken","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/l/lefty-i-beklerken/image/lefty-i-beklerken.jpg","link":"https://tiyatrolar.com.tr/tiyatro/lefty-i-beklerken","year":2015}, // 11 yıl önce
  {"id":"94869","title":"Ramiz İle Jülide","slug":"ramiz-ile-julide","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/r/ramiz-ile-julide/image/ramiz-ile-julide.jpg","link":"https://tiyatrolar.com.tr/tiyatro/ramiz-ile-julide","year":2015}, // 11 yıl önce
  {"id":"94868","title":"Kurnaz Aşıklar","slug":"kurnaz-asiklar","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/k/kurnaz-asiklar/image/kurnaz-asiklar.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kurnaz-asiklar","year":2015}, // 11 yıl önce
  {"id":"94844","title":"Vanya Dayı","slug":"vanya-dayi2","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/v/vanya-dayi2/image/vanya-dayi2.jpg","link":"https://tiyatrolar.com.tr/tiyatro/vanya-dayi2","year":2015}, // 11 yıl önce
  {"id":"94843","title":"Çamaşırhane","slug":"camasirhane","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/c/camasirhane/image/camasirhane.jpg","link":"https://tiyatrolar.com.tr/tiyatro/camasirhane","year":2015}, // 11 yıl önce
  {"id":"94838","title":"Kontrabas","slug":"kontrabas","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/k/kontrabas/image/kontrabas.jpg","link":"https://tiyatrolar.com.tr/tiyatro/kontrabas","year":2015}, // 11 yıl önce
  {"id":"94835","title":"Euridice'nin Elleri","slug":"euridice-nin-elleri","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/e/euridice-nin-elleri/image/euridice-nin-elleri.jpg","link":"https://tiyatrolar.com.tr/tiyatro/euridice-nin-elleri","year":2015}, // 11 yıl önce
  {"id":"94830","title":"Gözlerimi Kaparım Vazifemi Yaparım","slug":"gozlerimi-kaparim-vazifemi-yaparim","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/g/gozlerimi-kaparim-vazifemi-yaparim/image/gozlerimi-kaparim-vazifemi-yaparim.jpg","link":"https://tiyatrolar.com.tr/tiyatro/gozlerimi-kaparim-vazifemi-yaparim","year":2015}, // 11 yıl önce
  {"id":"94820","title":"Shakespeare Zorda","slug":"shakespere-zorda","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/s/shakespere-zorda/image/shakespere-zorda.jpg","link":"https://tiyatrolar.com.tr/tiyatro/shakespere-zorda","year":2015}, // 11 yıl önce
  {"id":"94818","title":"Grönholm Metodu","slug":"gronholm-metodu","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/g/gronholm-metodu/image/gronholm-metodu.jpg","link":"https://tiyatrolar.com.tr/tiyatro/gronholm-metodu","year":2015}, // 11 yıl önce
  {"id":"94815","title":"Son Tango","slug":"son-tango","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/s/son-tango/image/son-tango.jpg","link":"https://tiyatrolar.com.tr/tiyatro/son-tango","year":2015}, // 11 yıl önce
  {"id":"94811","title":"Yarasa","slug":"yarasa","company":"Ankara Devlet Opera ve Balesi","poster":"https://tiyatrolar.com.tr/files/activity/y/yarasa/image/yarasa.jpg","link":"https://tiyatrolar.com.tr/tiyatro/yarasa","year":2015}, // 11 yıl önce
  {"id":"94803","title":"Felatun Bey ile Rakım Efendi","slug":"felatun-bey-ile-rakim-efendi","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/f/felatun-bey-ile-rakim-efendi/image/felatun-bey-ile-rakim-efendi.jpg","link":"https://tiyatrolar.com.tr/tiyatro/felatun-bey-ile-rakim-efendi","year":2015}, // 11 yıl önce
  {"id":"94791","title":"Woyzeck Masalı","slug":"woyzeck-masali","company":"Tatbikat Sahnesi","poster":"https://tiyatrolar.com.tr/files/activity/w/woyzeck-masali/image/woyzeck-masali.jpg","link":"https://tiyatrolar.com.tr/tiyatro/woyzeck-masali","year":2015}, // 11 yıl önce
  {"id":"94782","title":"Gizli Oturum","slug":"gizli-oturum","company":"Bilkent Tiyatro","poster":"https://tiyatrolar.com.tr/files/activity/g/gizli-oturum/image/gizli-oturum.jpg","link":"https://tiyatrolar.com.tr/tiyatro/gizli-oturum","year":2015}, // 11 yıl önce
  {"id":"94778","title":"Söylentiler","slug":"soylentiler","company":"Ankara Devlet Tiyatrosu","poster":"https://tiyatrolar.com.tr/files/activity/s/soylentiler/image/soylentiler.jpg","link":"https://tiyatrolar.com.tr/tiyatro/soylentiler","year":2015}, // 11 yıl önce
];
