import type { ArchiveEntry } from "./types";

// Other PrimeTek work, from the posts that announced it (spec §4.3).
export const archiveEntries: ArchiveEntry[] = [
  {
    id: "designer-api",
    org: "primetek",
    date: "2018-04",
    title: "Designer API",
    note: "The Designer API, a SASS-based way of building PrimeFaces themes, announced in April 2018; the PrimeNG version followed in May with over 500 variables and a demo application.",
    source: "https://web.archive.org/web/20180526/https://www.primefaces.org/blog/",
  },
  {
    id: "primefaces-showcase",
    org: "primetek",
    date: "2018-06",
    title: "PrimeFaces Showcase redesign",
    note: "The PrimeFaces Showcase redone from the ground up and given a modern look that matches the PrimeNG and PrimeReact showcases.",
    source: "https://web.archive.org/web/20180706/https://www.primefaces.org/blog/",
  },
  {
    id: "sigma",
    org: "primetek",
    date: "2019-06",
    title: "Sigma",
    note: "A free open-source admin template for PrimeVue, built on Vue CLI, with two menu modes, light and dark schemes and a profile menu.",
    source: "https://web.archive.org/web/20190722/https://www.primefaces.org/blog/",
  },
  {
    id: "nova-luna",
    org: "primetek",
    date: "2018-08",
    title: "Nova and Luna themes",
    note: "Nova, a free open-source theme in light, dark and colored flavors, made with the PrimeNG Designer API and debuting in PrimeNG 6.1 RC1 in August 2018.",
    source: "https://web.archive.org/web/20180802/https://www.primefaces.org/blog/",
  },
  {
    id: "primeng-theme-designer-7",
    org: "primetek",
    date: "2018-12",
    title: "PrimeNG Theme Designer",
    note: "The PrimeNG Theme Designer upgraded to Angular 7, alongside PrimeNG 7.",
    source: "https://x.com/prime_ng/status/1070961512251080704",
  },
  {
    id: "saga-vela-arya",
    org: "primetek",
    date: "2020-08",
    title: "Saga, Vela and Arya themes",
    note: "Three free core themes, Saga, Vela and Arya, introduced as PrimeNG 10 began, alongside free Bootstrap and Material themes, with dark mode as standard.",
    source: "https://www.primefaces.org/blog/primeng-10-begins/",
  },
  {
    id: "sakai",
    org: "primetek",
    date: "2021-09",
    title: "Sakai",
    note: "A free admin template with a minimalist design and two menu modes: Vue in September 2021, then React in October 2021, Angular in January 2022 and Next.js in October 2022.",
    source: "https://www.primefaces.org/blog/sakai-free-vue-admin-template/",
  },
  {
    id: "tailwind-theme",
    org: "primetek",
    date: "2021-09",
    title: "Free Tailwind theme",
    note: "A free Tailwind-based theme for PrimeVue.",
    source: "https://x.com/primevue/status/1434846405818998790",
  },
  {
    id: "lara-themes",
    org: "primetek",
    date: "2021-11",
    title: "Lara themes",
    note: "New free Lara themes, released with PrimeVue 3.9.0 under the PrimeOne Design 2022 name; PrimeReact 7 and the PrimeNG 13 release candidate had shipped it a few days earlier.",
    source: "https://x.com/primevue/status/1461339072199278594",
  },
  {
    id: "visual-theme-designer-free",
    org: "primetek",
    date: "2023-07",
    title: "Visual Theme Designer for PrimeFaces",
    note: "The Visual Theme Designer opened to PrimeFaces users at no cost.",
    source: "https://x.com/primefaces/status/1684176428512821249",
  },
  {
    id: "theme-gallery",
    org: "primetek",
    date: "2023-09",
    title: "Theme Designer gallery",
    note: "A gallery for sharing designs made with the new Theme Designer.",
    source: "https://x.com/w00f/status/1699028097872371916",
  },
  {
    id: "aura",
    org: "primetek",
    date: "2024-01",
    title: "Aura theme",
    note: "Aura, an open source theme released with PrimeVue 3.47.0: ten color options and a Noir mode.",
    source: "https://x.com/primevue/status/1750202624069058637",
  },
  {
    id: "visual-theme-editor",
    org: "primetek",
    date: "2024-11",
    title: "Visual Theme Editor",
    note: "A visual editor for custom PrimeVue themes, from idea to release in under a week.",
    source: "https://x.com/w00f/status/1857050715224494345",
  },
  {
    id: "primevue-theme-designer",
    org: "primetek",
    date: "2025-02",
    title: "PrimeVue Theme Designer",
    note: "A new PrimeVue Theme Designer that adds cloud storage, a migration assistant, a visual editor and Figma-to-code generation.",
    source: "https://x.com/primevue/status/1892887414865011098",
  },
  {
    id: "primeng-theme-designer",
    org: "primetek",
    date: "2025-04",
    title: "PrimeNG Theme Designer",
    note: "A new PrimeNG Theme Designer that adds cloud storage, a migration assistant, a visual editor and Figma-based theme code generation.",
    source: "https://x.com/prime_ng/status/1912477580525027569",
  },
  {
    id: "figma-theme-code",
    org: "primetek",
    date: "2025-10",
    title: "Figma to Theme Code pipeline",
    note: "A CI pipeline that automatically converts Figma designs into theme code, announced for the following week.",
    source: "https://x.com/primevue/status/1976629074488619089",
  },
];
